[package]
name = "rusty-playground"
version = "0.1.0"
authors = ["Bob Chatman <bob.chatman@gmail.com>"]
publish = false

[features]
default = []

[[bin]]
name = "rusty-playground"
path = "src/main.rs"

[dependencies]
log = "0.4.1"
winit = "0.10.0"
env_logger = "0.5.2"
time = "0.1.39"
os_type="*"
